blank_issues_enabled: false
contact_links:
    - name: ğŸ—£ï¸ Ask question
      url: https://github.com/jonnitto/Jonnitto.PrettyEmbedPresentation/discussions/category_choices
      about: Please ask and answer questions in discussions
